apiVersion: v1
data:
    token: ENC[AES256_GCM,data:uQDeHQ==,iv:+0BKyCg5JMD2h9BCp0UT3Mh1RwYfY5AOB3BT/owPGJY=,tag:SNdqquR/54/o/En+2UC9Zw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: kbot
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/prometheus-407701/locations/global/keyRings/kbot-sops-flux/cryptoKeys/kbot-sops-key-flux
          created_at: "2024-01-26T22:47:34Z"
          enc: CiQAzT3v+U0cgYCMhZDTF8Ol8MW1e40IArCegqlB9rrsMQYDuy0SSQClIEphMuHaEG2/0u/QwRbipo97QdySSXFzH7ox8CYfhJfM6K8SY+zryWl9x4AteLmkQdqdXtm7OYRmSbcUvf24RPW8NFLplKE=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-26T22:47:34Z"
    mac: ENC[AES256_GCM,data:3zrjbeVCTiCEV7v+eUtRRMmmX/bVzxbqOAy3r12YTqkrir176PUfnP5AKn1I7I0Tf19E7Uq9mg44F8wThbQguyFd10ZO0QlTgPu+3IxUdesSe9+Ys1nxYDTmSyQc7JcTT4dkD573M+y5vHjrq+DTXmHVV6PP9AuZQxXolbQzZEE=,iv:DPoVjaPzexLPp3vgGhr6aIdKw6MfoiXsPLj2SBML90A=,tag:RrPpL6Afnu8b6d+FKJGFoA==,type:str]
    pgp: []
    encrypted_regex: ^(token)$
    version: 3.8.1
