grafana:
# # Additional data source
# additionalDataSources:
# - name: Tempo
#   type: tempo
#   uid: tempo
#   access: proxy
#   url: http://tempo-query-frontend.monitoring.svc.cluster.local:3100



additionalDataSources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  jsonData:
    httpMethod: GET

- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: true



