# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: "dkzippa"
  tag: "v1.0.8-f6b2778"
  arch: amd64
  os: linux
secret:
  env: "TELE_TOKEN"
  name: "kbot"
  key: "token"
