name: KBOT-CICD

env:
  REGISTRY: ghcr.io
  APP: "prometheus-kbot"

on:
  push:
    branches:
      - develop

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: make-test
        run: make test

      - name: ghcr-login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: make-build-push
        env:
          REGISTRY: ${{ env.REGISTRY }}
          APP: ${{ env.APP }}
          TARGETARCH: amd64
          TARGETOS: linux
        run: make image push REGISTRY=${{env.REGISTRY}}/${{ github.actor }} APP=${{ env.APP }}

      - name: make-clean
        run: make clean
