name: kbot-cicd

env:
  REGISTRY: ghcr.io
  APP: "prometheus-kbot"    
  GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }} 

on:
  push:
    branches:
      - develop
      - develop-sops2

jobs:
  # ci:
  #   name: CI
  #   runs-on: ubuntu-latest
  #   # permissions:
  #   #   contents: read
  #   #   packages: write

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: make-test
  #       run: make test

  #     - name: ghcr-login
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

  #     - name: make-build-push
  #       env:
  #         REGISTRY: ${{ env.REGISTRY }}
  #         APP: ${{ env.APP }}
  #         TARGETARCH: amd64
  #         TARGETOS: linux
  #       run: make image push REGISTRY=${{env.REGISTRY}}/${{ github.actor }} APP=${{ env.APP }}

  #     - name: make-clean
  #       run: make clean

  cd:
    name: CD
    runs-on: ubuntu-latest
    
    # permissions:
    #   id-token: 'write'
      
    # needs:
    #   - ci
    
    env:
      GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }} 

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0          
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          
      - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION)' ./helm/values.yaml


      - name: create_TELE_TOKEN_BASE64
        env:
          TELE_TOKEN: ${{ secrets.TELE_TOKEN }}
        run: |-
          echo $TELE_TOKEN
          echo "TELE_TOKEN_BASE64=$(echo $TELE_TOKEN | base64 )" >> $GITHUB_ENV;        
          echo $TELE_TOKEN_BASE64
  
      - uses: mikefarah/yq@master
        with:
          cmd: yq -i -v '.data.token=$TELE_TOKEN_BASE64' ./helm/templates/secret.yaml
  
      - name: check_teletoken
        run: cat ./helm/templates/secret.yaml

      # - id: gcp-auth
      #   uses: 'google-github-actions/auth@v2'
      #   name: gcpauth
      #   with:
      #     project_id: 'prometheus-407701'
      #     create_credentials_file: 'true'
      #     workload_identity_provider: "projects/92496117895/locations/global/workloadIdentityPools/prometheus-kbot-github/providers/prometheus-kbot-github-provider2"
      #     service_account: "kustomize-controller@prometheus-407701.iam.gserviceaccount.com"
      #     export_environment_variables: 'false'
      
      # - name: github_login 
      #   run: |-
      #     echo "GH_TOKEN1: $GH_TOKEN"          
      #     echo "PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}"
      #     # echo "GITHUB_TOKEN1: ${{ secrets.GITHUB_TOKEN }}"
      #     # echo "GITHUB_TOKEN2: $GITHUB_TOKEN"
      #     # echo "GITHUB_TOKEN3: ${GITHUB_TOKEN}"
      #     gh auth login --with-token="true"
          
      - name: push new helm version
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "bump version in helm values to $VERSION"
          git push
