name: kbot-cicd

env:
  REGISTRY: ghcr.io
  APP: "prometheus-kbot"

on:
  push:
    branches:
      - develop
      - develop-sops2

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: make-test
        run: make test

      - name: ghcr-login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: make-build-push
        env:
          REGISTRY: ${{ env.REGISTRY }}
          APP: ${{ env.APP }}
          TARGETARCH: amd64
          TARGETOS: linux
        run: make image push REGISTRY=${{env.REGISTRY}}/${{ github.actor }} APP=${{ env.APP }}

      - name: make-clean
        run: make clean

  cd:
    name: CD
    runs-on: ubuntu-latest

    needs:
      - ci

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION)' ./helm/values.yaml

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "bump version in helm values to $VERSION"
          git push
